config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'pages#home'
 
  devise_for :users 
   

  resources :weektimes do
  resources :worktimes 
  end
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/weektime.rb
#    create_table :weektimes do |t|
#      t.references :user, null: false, foreign_key: true
#      t.date :dateweek, null: false
#      t.time :weekhour
#      t.boolean :accord, default: false
#
#      t.timestamps
#
#      

class Weektime < ApplicationRecord
  belongs_to :user

  has_many :worktimes , dependent: :delete_all
  accepts_nested_attributes_for :worktimes

   
  validates_presence_of :dateweek

  def update_weekhour
    self.update_columns(weekhour: weekhour)
  end






end

app/controllers/weektimes_controller.rb
class WeektimesController < ApplicationController
  before_action :set_weektime, only: %i[ show edit update destroy ]

  before_action :only => [:new, :edit] do
    redirect_to new_user_session_path unless current_user 
  end




  # GET /weektimes or /weektimes.json
  def index
    if current_user.admin
    @weektimes = Weektime.all
    else
    @weektimes = current_user.weektimes 
    end
    
    
  end

  # GET /weektimes/1 or /weektimes/1.json
  def show

   @worktimes = @weektime.worktimes
   @weektime.weekhour = 0

   @worktimes.each do |wo|
    @weektime.weekhour = @weektime.weekhour + wo.totaltime
   end

   @weektime.update_weekhour

  
   
  end

  # GET /weektimes/new
  def new
    @weektime = current_user.weektimes.build
  end

  # GET /weektimes/1/edit
  def edit
  end

  # POST /weektimes or /weektimes.json
  def create
    @weektime = current_user.weektimes.build(weektime_params)
  #  @weektime.user_id = current_user.id
    @weektime.weekhour = 0

    respond_to do |format|
      if @weektime.save
        format.html { redirect_to weektime_url(@weektime), notice: "Weektime was successfully created." }
        format.json { render :show, status: :created, location: @weektime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weektime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weektimes/1 or /weektimes/1.json
  def update
    respond_to do |format|
      if @weektime.update(weektime_params)
        format.html { redirect_to weektime_url(@weektime), notice: "Weektime was successfully updated." }
        format.json { render :show, status: :ok, location: @weektime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weektime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weektimes/1 or /weektimes/1.json
  def destroy
    @weektime.destroy
       respond_to do |format|
        format.html { redirect_to weektimes_url(current_user), notice: "Weektime was successfully destroyed." }
        format.json { head :no_content }
      end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weektime
      @weektime = Weektime.find(params[:id])
    end

 

    # Only allow a list of trusted parameters through.
    def weektime_params
      params.require(:weektime).permit(:user_id, :dateweek, :weekhour, :alltime, :accord, :worktime_id =>[] )
    end
end

app/helpers/weektimes_helper.rb
module WeektimesHelper
end

app/views/weektimes/_form.html.erb
  <div class="border p-3 mb-4 container">
    <%= simple_form_for(@weektime) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
    
    
        <%= f.input :dateweek, as: :date, html5: true, label: "Selectionne le jour de la semaine " , hint: "selection le jour d'une semaine"%>
      
    
      <div class="form-actions text-center ">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>
</br>

app/views/weektimes/_weektime.html.erb
  <tr>
    <td class="text-center"><%= weektime.user_id %></td>
    <td class="text-center"><%= weektime.dateweek.cweek %> | <%= weektime.dateweek.strftime("%Y-%m") %></td>
    <td class="text-center"><%= weektime.worktimes.size %></td>
    <td class="text-center"><%= weektime.weekhour %></td>
    <td class="text-center"><%= weektime.accord %></td>
    <td class="text-center"><%= link_to "Show", weektime %></td>
  </tr>
      

app/views/weektimes/edit.html.erb
<h1>Editing weektime</h1>

 <%= render partial: "weektimes/form"%>
</br>

<div>
  <%= link_to "Show this weektime", @weektime %> |
  <%= link_to "Back to weektimes", weektimes_path %>
</div>

app/views/weektimes/index.html.erb
<h1 class="text-center">Weektimes</h1>

      <div class="container">
 
      <table class="table table-sm">
        <thead class="thead-light">
          <tr>
            <th class="text-center"><strong> #</strong></th>
            <th class="text-center"><strong>Date</strong></th>
            <th class="text-center"><strong>Nbrs horaire</strong></th>
            <th class="text-center"><strong>H/Total</strong></th>
            <th class="text-center"><strong>Validation</strong></th>
            <th class="text-center"></th>
          </tr>
        </thead>
      <tbody>

  <% @weektimes.each do |weektime| %>
    <%= render weektime %>
  <% end %>

</tbody>
        <thead class="thead-light">
          <tr>
            <th> </th>
            <th> </th>
            <th> </th>
            <th> </th>
            <th> </th>
            <th> </th>
          </tr>
        </thead>
      </table>
      
<hr>

  <%= button_to "New weektime", new_weektime_path, method: :get %>
</div> 

</br>
</br>

<div class= "container">
  <%= button_to "Dashbord", root_path, method: :get %>
</div>  

app/views/weektimes/new.html.erb
<div >
 
  <h1 class="text-center">New weektime</h1>
</div>

 <%= render partial: "weektimes/form"%>
    
  <div class="container">
    <%= button_to "Voir toutes mes heures", weektimes_path, method: :get, class: "text-right"%>
  </div>
  

app/views/weektimes/show.html.erb
 </br>
<div class="border p-3 mb-0 container">
  <h2 class="text-center" > <strong> Semaine : </strong><%= @weektime.dateweek.cweek %> | <strong> Date : </strong><%= @weektime.dateweek.strftime("%Y-%m")    %></h2>
  <hr>
  <div class="container">
       <table class="table table-sm">
        <thead class="thead-light">
          <tr>
            <th><strong>Jour</strong></th>
            <th><strong>debut</strong></th>
            <th><strong>fin</strong></th>
            <th><strong>H/Total </strong></th>
          
          </tr>
        </thead>
    <%if @worktimes.empty? %> 
            <tr>
              <td> </td>
              <td> </td>
              <td> </td>
              <td> </td>
            </tr>
    <% else %>   
      <tbody>   
          <% @worktimes.each do |work| %>
            <tr>
              <td><%= work.daytime %> </td>
              <td><%= work.gotime.to_fs(:time) %></td>
              <td><%= work.endtime.to_fs(:time) %></td> 
              <td><%= Time.at(work.totaltime).utc.strftime("%HH %Mmin") %></td>
            </tr>
          <% end %>
      </tbody>
    <%end%>  
        <thead class="thead-light">
          <tr>
            <th>valider: <%= @weektime.accord %></th>
            <th> </th>
            <th> </th>
            <th><%= Time.at(@weektime.weekhour).utc.strftime("%HH %Mmin") %> </th>
            
          </tr>
        </thead>
      </table>
  </div>
  <hr>
  <div class="container ">
    <div class="text-center">
      <%= button_to "+ Ajoute une heure", new_weektime_worktime_path(@weektime), method: :get %>
    </div>

    <div class="">
      <%= button_to "Modifier la date de la semaine", edit_weektime_path(@weektime), method: :get %> </br>
      <%= button_to "Supprimer la feuilles d'heure", @weektime, method: :delete, form: { data: { 'turbo-confirm': 'Vous etes sur ?' } }  %>
    </div>
  </div>
</div>

</br>
<div class="container">
<%= button_to "Dashbord", root_path, method: :get %>
</div>