config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'pages#home'
 
  devise_for :users 
   

  resources :weektimes do
  resources :worktimes 
  end
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/worktime.rb
#   create_table :worktimes do |t|
#  t.references :weektime, null: false, foreign_key: true
#  t.time :daytime
#  t.time :gotime, null: false
#  t.time :endtime, null: false
#  t.time :totaltime
#  
#  t.timestamps
# 
 class Worktime < ApplicationRecord
  belongs_to :weektime
  
  enum daytime:{lundi:1, mardi:2, mercredi:3, jeudi:4, vendredi:5, samedi:6, dimanche:0}
 
  # attr_reader :set_jour
  attr_accessor :flash_alert_message

  before_validation :insert_weektime_id, on: [ :create, :update ]
  
  validates :daytime, presence: true
  validates :gotime, presence: true
  validates :endtime, presence: true

 
  after_validation :calcul_heure, on: [ :create, :update ]

  after_validation :validate_negative_heure, on: [ :create, :update ]
  after_validation :calcul_max_heur, on: [ :create, :update ]
 


#  def set_jour  
#    self.worktime.wday 
#  end


  private

 
  def insert_weektime_id
    if self.weektime.id.nil?
      self.flash_alert_message  = "Erreur weektimes is nil" 
      raise ActiveRecord::Rollback 
    end
  end

 
  def calcul_heure
    self.totaltime = self.endtime - self.gotime  
  end

  def calcul_max_heur
    
    if self.totaltime > 64800 # valeur 18h //3600 sec = 60 minutes
      self.flash_alert_message = "Erreur trop d'heure saisie" 
      raise ActiveRecord::Rollback 
    end  
  end

 
#  def empty_day  
#    self.flash_alert_message = "Sasire jour" if self.daytime.nil? 
#  end

  def validate_negative_heure
    if self.totaltime.negative? || self.totaltime == 0 
      self.flash_alert_message = "Erreur de sasie des heures" 
      raise ActiveRecord::Rollback 
    end  
  end

end

app/controllers/worktimes_controller.rb
class WorktimesController < ApplicationController
  before_action :set_worktime, only: %i[ show edit update destroy ]
  before_action :set_weektime, only: %i[ show new edit create update destroy ]
  after_action :flash_alert_message, :except => :index


  # GET /worktimes or /worktimes.json
  def index
    @worktimes = Worktime.all
  end

  ## GET /worktimes/1 or /worktimes/1.json
  #def show
  #end

  # GET /worktimes/new
  def new
  
    @worktime = @weektime.worktimes.build
   

  end

  # GET /worktimes/1/edit
  def edit
  end

  # POST /worktimes or /worktimes.json
  def create
     @worktime = @weektime.worktimes.build(worktime_params)
  
    respond_to do |format|
      if @worktime.save
        format.html { redirect_to weektime_url(@weektime) , notice: "Worktime was successfully created." }
        #format.json { render :show, status: :created, location: @weektime }
      else
        format.html { render :new, status: :unprocessable_entity }
        #format.json { render json: @worktime.errors, status: :unprocessable_entity }
      end
    end
 
end

  # PATCH/PUT /worktimes/1 or /worktimes/1.json
  def update
    respond_to do |format|
      if @worktime.update(worktime_params)
        format.html { redirect_to worktime_url(@worktime), notice: "Worktime was successfully updated." }
        format.json { render :show, status: :ok, location: @worktime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worktime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worktimes/1 or /worktimes/1.json
  def destroy
    @worktime.destroy

    respond_to do |format|
      format.html { redirect_to worktimes_url, notice: "Worktime was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def flash_alert_message
    return unless @worktime.flash_alert_message.present?
    flash[:alert] = @worktime.flash_alert_message
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worktime
      @worktime = Worktime.find(params[:id])
    end
    def set_weektime
      @weektime = Weektime.find(params[:weektime_id])
    end
    

  


    # Only allow a list of trusted parameters through.
    def worktime_params
      params.require(:worktime).permit(:weektime_id, :gotime, :endtime, :totaltime, :daytime)
    end



end

app/helpers/worktimes_helper.rb
module WorktimesHelper
end

app/views/worktimes/_form.html.erb
<div class=" container border p-3 mb-4 ">
</br>
  <%= simple_form_for [@weektime, @worktime] do |f| %>
    <%= f.error_notification %>
    <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    
    <div>
      <%#= f.input :daytime,  wrapper: :horizontal_collection_inline, collection: Worktime.daytimes.keys  %>
      <%= f.input :daytime, as: :radio_buttons, collection:Worktime.daytimes.keys , wrapper: :horizontal_collection_inline %>

    </div>
    <div class="form-inputs">
      <%= f.input :gotime, as: :time %>
      <%= f.input :endtime, as: :time %>
     
    </div>
  </br>
    <div class="text-center">
      <%= f.button :submit %>
    </div>
  </br>
<% end %>

</div>

app/views/worktimes/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Horaire travailler</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "worktimes/form", worktime: worktime %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/worktimes/_worktime.html.erb
<div id="<%= dom_id worktime %>">
  <p>
    <strong>Weektime:</strong>
    <%= worktime.weektime_id %>
  </p>

  <p>
    <strong>Gotime:</strong>
    <%= worktime.gotime %>
  </p>

  <p>
    <strong>Endtime:</strong>
    <%= worktime.endtime %>
  </p>

</div>

app/views/worktimes/edit.html.erb
<h1>Editing worktime</h1>

  <%= render partial: "worktimes/form"%>


<br>

<div>
   <%= link_to "Back to worktimes", weektime_worktime_path(@weektime) %>
</div>

app/views/worktimes/edit.turbo_stream .erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "worktimes/form_modal", locals: { worktime: @worktime } %>
<% end %>

app/views/worktimes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Worktimes</h1>

<div id="worktimes">
  <% @worktimes.each do |worktime| %>
    <%= render worktime %>
    <p>
      <%#= link_to "Show this worktime", weektime_worktime_url(worktime) %>
    </p>
  <% end %>
</div>

<%= button_to "New worktime", new_weektime_worktime_path,method: :get %>

app/views/worktimes/new.html.erb
<div >
 
  <h1 class="text-center">New worktime</h1>
</div>


    <%= render partial: "worktimes/form"%>


<br>

<div class= "container">
  <%= button_to "feuille d'heure", weektime_path(@weektime), method: :get %>
</div>

app/views/worktimes/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "worktimes/form_modal", locals: { worktime: @worktime } %>
<% end %>